<?php

namespace SqlSetupBundle\Repository;

/**
 * ScreenwriterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScreenwriterRepository extends \Doctrine\ORM\EntityRepository
{
}
